import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import SessionProvider from "@/components/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col`}>
        <SessionProvider>
          <Header />
          <div className="flex flex-1 overflow-hidden">
            <Sidebar />
            <main className="flex-1 overflow-y-auto md:ml-0">{children}</main>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
